def gv

pipeline {
    agent any
    stages {
        stage("init") {
            steps {
                script {
                    gv = load "./java-maven-app/script.groovy"
                }
            }
        }
        stage("build") {
            steps {
                script {
                    gv.buildApp()
                }
            }
        }
        stage("test") {
            input {
                message "Select the evironment for the deployment"
                ok "Done"
                parameters {
                    choice(name: "ENV", choices: ["dev", "prod"], description: "Selecting Environment")
                }
            }
            steps {
                script {
                    echo "Deploying to ${ENV}"
                    gv.testApp()
                }
            }
        }
        stage("deploy") {
            steps {
                script {
                    gv.deployApp()
                }
            }
        }
    }   
}